use_frameworks!

platform :ios, '9.0'

target 'LukaSDK_Example' do
  pod 'LukaSDK', :path => '../'

  target 'LukaSDK_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if Gem::Version.new('8.0') > Gem::Version.new(config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'])
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
      
      config.build_settings['SWIFT_VERSION'] = '5.1'
    end
    
    puts "#{target.name}"
  end
end
